name: Manual Trigger Workflow with Parameters

on:

  push:

   branches: ["main"]
  pull_request:
   branches: ["main"]
   
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Greetings
      run: echo "Hello World"
